# Generated by Django 4.2.7 on 2025-09-16 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_sboprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.college'),
        ),
    ]
