# Generated by Django 4.2.7 on 2025-09-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendee_college'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='sign_in_time',
            new_name='sign_in_am',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='sign_out_time',
            new_name='sign_in_pm',
        ),
        migrations.AddField(
            model_name='attendance',
            name='sign_out_am',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='sign_out_pm',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
